# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/trove_newspaper_images/',
                'doc_host': 'https://wragge.github.io',
                'git_url': 'https://github.com/wragge/trove_newspaper_images/tree/master/',
                'lib_path': 'trove_newspaper_images'},
  'syms': { 'trove_newspaper_images.articles': { 'trove_newspaper_images.articles.download_images': ( 'articles.html#download_images',
                                                                                                      'trove_newspaper_images/articles.py'),
                                                 'trove_newspaper_images.articles.get_article_boxes': ( 'articles.html#get_article_boxes',
                                                                                                        'trove_newspaper_images/articles.py'),
                                                 'trove_newspaper_images.articles.get_box': ( 'articles.html#get_box',
                                                                                              'trove_newspaper_images/articles.py'),
                                                 'trove_newspaper_images.articles.main': ( 'articles.html#main',
                                                                                           'trove_newspaper_images/articles.py')}}}