# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_box": "00_articles.ipynb",
         "get_article_boxes": "00_articles.ipynb",
         "download_images": "00_articles.ipynb"}

modules = ["articles.py"]

doc_url = "https://wragge.github.io/trove_newspaper_images/"

git_url = "https://github.com/wragge/trove_newspaper_images/tree/master/"

def custom_doc_links(name): return None
